config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users
  get 'welcome/index'

  namespace :api, defaults: {format: 'json'} do
    devise_for :users
    resources :rooms
  end

   root 'welcome#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_save :ensure_authentication_token

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable
  #attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  has_many :rooms
end

app/controllers/api/registrations_controller.rb
module Api
  class RegistrationsController < ApplicationController
    respond_to :json
    skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }

    def create
      user = User.new(user_params)

      if user.save
        @userData = User.find(user.id)
        my_data = {status: 1, user: {id: user.id, token: @userData.authentication_token }}
        render :json=> my_data, :status=> 201
        return
      else
        warden.custom_failure!
        render :json=> user.errors, :status=>422
      end
    end
    private
    def user_params
      params.require(:registration).permit(:email, :password)
    end
  end
end

app/controllers/api/rooms_controller.rb
module Api
  class RoomsController < ApplicationController
    before_filter :authenticate_token!, :only => [:create, :update, :destroy]
    before_filter :authorize_user!, :only => [:update, :destroy]

    respond_to :json


    def index
      respond_with Room.all
    end

    def show
      begin
        @room = Room.find(params[:id])
        respond_with Room.find(params[:id])
      rescue
        error(404, 404, "Room #{params[:id]} does not exist.")
      end
    end

    def create
      respond_with Room.create(params[:room])
    end

    def update
      if Room.update(params[:id], params[:room])
         render :json=> Room.find(params[:id])
        return
      else
        render :json=> Room.update(params[:id], params[:room]).errors, :status=>422
      end
    end

    def destroy
      respond_with Room.destroy(params[:id])
    end

    private
    def authenticate_token!
      if User.find_by_id(params[:user_id]).nil?
        render :json => {:message => "User does not exist."}, :success => false, :status => 422
      elsif User.find_by_id(params[:user_id]).authentication_token == params[:authentication_token]
        #params[:room][:user_id] = params[:user_id]
        true
      else
        render :json => {:message => "Missing correct authentication token."}, :success => false, :status => 401
      end
    end

    def authorize_user!
      if Room.find(params[:id]).user_id == params[:user_id].to_i
        true
      else
        render :json => {:message => "User not authorized to change this content"}, :success => false, :status => 401
      end
    end

  end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
    @user = @room.user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])
    @room.user = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<%= link_to "Sign Out" ,destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign In" , new_user_session_path %> |
<%= link_to "Sign Up" , new_user_registration_path %>
<% end %>
<% debug current_user %>
  <!-- <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %> -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.name %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<%= debug @room.user %>
<p>
<b>Name:</b>
<%= @room.name %>
</p>

<p>
<b>User ID:</b>
<%= @room.user.id %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>